#!/bin/bash
start_time =

# Then, run the Python script
python3 stbltr.py

python3 autoclnckies.py

# Run the Bash script
bash lie3.sh
bash lie.sh

# Then, run the Python script
python3 stbltr.py

python3 autoclnckies.py

# Run the Bash script
bash lie3.sh
bash lie.sh

# Then, run the Python script
python3 stbltr.py

python3 autoclnckies.py

# Run the Bash script
bash lie3.sh
bash lie.sh
# Then, run the Python script
python3 stbltr.py

python3 autoclnckies.py

# Run the Bash script
bash lie3.sh
bash lie.sh

# Then, run the Python script
python3 stbltr.py

python3 autoclnckies.py

# Run the Bash script
bash lie3.sh
bash lie.sh

time.time()
